"""Generate ``results/results_table.md`` from ``results/sweep_summary.csv``.

Aggregates best-FD (per the paper, the reported FD is the best over training,
since generation quality decays after ~700 iters) as mean ± std across seeds,
per model and digit, and emits a Markdown table plus per-seed rows. Paper
reference numbers (Fig. 5) are included for context.

Usage::

    python utils/make_table.py
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent.parent

# Paper Fig. 5 reference FD (lower is better). Approximate reads from the plot.
PAPER_FD = {
    "quantum": {0: 50, 5: 47, 9: 47},
    "classical": {0: 45, 5: 47, 9: 47},
    "random_decoder": {0: 73, 5: 53, 9: 51},
}
LABELS = {
    "quantum": "LatentQGAN — gate / Qiskit (this work)",
    "merlin": "LatentQGAN — MerLin photonic (this work)",
    "classical": "LatentGAN — classical iso-param (this work)",
    "random_decoder": "RandomDecoder (this work)",
}
ORDER = ["quantum", "merlin", "classical", "random_decoder"]


def main() -> None:
    summary = HERE / "results" / "sweep_summary.csv"
    rows = list(csv.DictReader(open(summary)))
    # Use best_fd (paper reports the best FD reached during training).
    by_md: dict[tuple[str, int], list[float]] = defaultdict(list)
    per_seed: list[tuple[str, int, int, float, float]] = []
    params: dict[str, int] = {}
    for r in rows:
        m, d, s = r["model"], int(r["digit"]), int(r["seed"])
        best = float(r["best_fd"]) if r["best_fd"] else float("nan")
        final = float(r["final_fd"]) if r["final_fd"] else float("nan")
        by_md[(m, d)].append(best)
        per_seed.append((m, d, s, best, final))
        params[m] = int(r["gen_params"]) if r["gen_params"] else 0

    digits = sorted({int(r["digit"]) for r in rows})
    n_seeds = max((len(v) for v in by_md.values()), default=1)

    def cell(m: int, d: int) -> str:
        vals = by_md.get((m, d), [])
        if not vals:
            return "–"
        mu = np.mean(vals)
        sd = np.std(vals) if len(vals) > 1 else 0.0
        return f"{mu:.1f} ± {sd:.1f}" if len(vals) > 1 else f"{mu:.1f}"

    out = []
    out.append("# Results table — LatentQGAN reproduction\n")
    out.append(
        f"Best FD reached during training, mean ± std over {n_seeds} "
        f"seed(s). Reduced compute: AE trained with SGD for 40 epochs on 20k "
        "MNIST images (paper: 100 epochs, full MNIST); QGAN 1000 iters "
        "batch 8 (paper: 490 iters batch 1). Lower FD is better. "
        "Auto-generated by `utils/make_table.py`.\n"
    )

    out.append("## Aggregated best FD (this work) vs paper Fig. 5\n")
    header = "| Model | " + " | ".join(f"Digit {d}" for d in digits) + " | Gen params |"
    sep = "|-------|" + "|".join(["--------:"] * len(digits)) + "|-----------:|"
    out.append(header)
    out.append(sep)
    for m in ORDER:
        cells = " | ".join(cell(m, d) for d in digits)
        out.append(f"| **{LABELS[m]}** | {cells} | {params.get(m, 0)} |")
    # paper rows
    for m in ["quantum", "classical", "random_decoder"]:
        cells = " | ".join(str(PAPER_FD[m].get(d, "–")) for d in digits)
        name = {
            "quantum": "LatentQGAN (paper)",
            "classical": "LatentGAN classical (paper)",
            "random_decoder": "RandomDecoder (paper)",
        }[m]
        out.append(f"| {name} | {cells} | – |")
    out.append("")

    out.append("## Per-seed values (best / final FD)\n")
    out.append("| Model | Digit | Seed | Best FD | Final FD |")
    out.append("|-------|------:|-----:|--------:|---------:|")
    for m, d, s, best, final in sorted(per_seed):
        out.append(f"| {m} | {d} | {s} | {best:.1f} | {final:.1f} |")
    out.append("")

    path = HERE / "results" / "results_table.md"
    path.write_text("\n".join(out) + "\n")
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
