"""Render Mario level sequences as images, as in the original paper.

The Moth open-data notebook renders levels with a private ``archeo``
encoder that is not part of the public dump. The mechanism, however, is
simple and fully recoverable from the packaged data: level 1-2 is a
2512x240 image of 157 columns, each 16 px wide, and the packaged
``mario_level_1-2.json`` sequence assigns one of 32 feature indices to
every column. Each feature therefore corresponds to a unique 16x240
tile, and rendering a sequence is tile concatenation.

The tile atlas is rebuilt from the original level image + sequence (the
tile for feature ``k`` is the column at the first position where the
sequence equals ``k``) and verified against every other occurrence, so
the reconstruction cannot silently drift from the authors' mapping.

Usage (from the paper directory):

    # original level
    python utils/render_level.py --original --out results/level_original.png
    # one of the authors' released sequences (pickle from reference_data)
    python utils/render_level.py \
        --pickle ../../data/qrc_level_generation/reference_data/SMB/6_qubits/Aer/Sequences_level_1-2_beta_1_Aer.p \
        --index 0 --out results/level_reference_T1.png
    # a sequence generated by one of our runs
    python utils/render_level.py --npz outdir/<RUN>/generated_sequences.npz \
        --temperature 1 --index 0 --out results/level_qrc_T1.png
"""

from __future__ import annotations

import argparse
import json
import pickle
from pathlib import Path

import numpy as np
from PIL import Image

PROJECT = Path(__file__).resolve().parents[1]
DATA_ROOT = PROJECT.parents[1] / "data" / "qrc_level_generation"
LEVEL_IMAGE = DATA_ROOT / "reference_data" / "SMB" / "original_levels" / "1-2-moth.png"
LEVEL_JSON = DATA_ROOT / "mario_level_1-2.json"
UNIT = 16


def build_atlas() -> tuple[dict[int, Image.Image], list[int]]:
    """Feature index -> 16px column tile, verified over all occurrences."""
    img = Image.open(LEVEL_IMAGE)
    payload = json.loads(LEVEL_JSON.read_text())
    sequence = [int(v) for v in payload["sequence"]]
    if img.size[0] != UNIT * len(sequence):
        raise ValueError(
            f"Level image width {img.size[0]} != {UNIT} * sequence length "
            f"{len(sequence)}"
        )
    atlas: dict[int, Image.Image] = {}
    arrays: dict[int, np.ndarray] = {}
    for i, feat in enumerate(sequence):
        tile = img.crop((i * UNIT, 0, (i + 1) * UNIT, img.size[1]))
        arr = np.asarray(tile)
        if feat not in atlas:
            atlas[feat] = tile
            arrays[feat] = arr
        elif not np.array_equal(arrays[feat], arr):
            raise ValueError(
                f"Column {i} (feature {feat}) differs from the first "
                f"occurrence of that feature — mapping mismatch"
            )
    missing = set(range(payload["num_features"])) - set(atlas)
    if missing:
        raise ValueError(f"Features never seen in the original level: {missing}")
    return atlas, sequence


def render(sequence, atlas: dict[int, Image.Image]) -> Image.Image:
    tiles = [atlas[int(f)] for f in sequence]
    height = tiles[0].size[1]
    out = Image.new("RGB", (UNIT * len(tiles), height))
    for i, tile in enumerate(tiles):
        out.paste(tile, (i * UNIT, 0))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    source = ap.add_mutually_exclusive_group(required=True)
    source.add_argument(
        "--original", action="store_true", help="render the original level 1-2 sequence"
    )
    source.add_argument(
        "--pickle", type=Path, help="authors' released sequence pickle (.p)"
    )
    source.add_argument(
        "--npz", type=Path, help="generated_sequences.npz from one of our runs"
    )
    ap.add_argument(
        "--temperature", default="1", help="npz only: temperature key, e.g. 1 or 30"
    )
    ap.add_argument(
        "--index",
        type=int,
        default=0,
        help="which sequence to render from a multi-sequence source",
    )
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    atlas, original_sequence = build_atlas()
    if args.original:
        sequence = original_sequence
    elif args.pickle:
        with args.pickle.open("rb") as handle:
            sequences = pickle.load(handle)
        sequence = sequences[args.index]
    else:
        z = np.load(args.npz)
        key = f"T_{float(args.temperature)}"
        if key not in z:
            raise KeyError(f"{key} not in {args.npz.name}; keys: {list(z.keys())}")
        sequence = z[key][args.index]

    image = render(sequence, atlas)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    image.save(args.out)
    print(f"wrote {args.out} ({image.size[0]}x{image.size[1]})")


if __name__ == "__main__":
    main()
