"""Plot beta vs N and elapsed time vs N for one or more runs.

Each run is named by its config; the results are located by hashing that config
(see :mod:`lib.config`), so plotting is just "give me the configs I ran"::

    python plotter.py -f configs/obliq_maxclique.json configs/qaoa_maxclique.json -o comparison.png
    python plotter.py -f obliq_maxclique.json -e          # exact per-instance beta

Two beta normalizations are available:

* default -- the Q-score standard's *asymptotic* baselines. Deflates beta
  noticeably below ``N ~ 10``, so small-N curves plateau well short of 1.
* ``-e``   -- *exact* beta: every instance is scored against its own graph's
  optimum. The instances are regenerated by replaying the run's seed sequence,
  which is why they must be sampled through :func:`utils.graphs.sample_instance_graph`
  (the same function the sweep used) rather than ``nx.erdos_renyi_graph``.

Exact beta re-solves every instance, once per config. When several configs share a
sweep (same problem, sizes, seed and instance count) the optima are identical, so
they are computed once and cached across configs.
"""

from __future__ import annotations

import argparse
import json
import os
from itertools import cycle

import matplotlib.pyplot as plt
import numpy as np
from lib.config import RESULTS_FILE, config_hash, load_config, run_dir
from lib.seeding import derive_seed
from utils.graphs import sample_instance_graph
from utils.max_clique import average_naive_clique_size, calculate_beta_max_clique
from utils.max_cut import calculate_beta_max_cut
from utils.qubo import exact_optimum

PLOTS_DIR = "plots"

#: Q-score beta threshold: the largest N whose mean beta clears this is the Q-score.
BETA_THRESHOLD = 0.2

#: Q-score per-instance time limit, in seconds.
TIME_LIMIT = 60


def parse_args() -> argparse.Namespace:
    """Parse the plotting CLI."""
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-f",
        "--file",
        dest="configs",
        nargs="+",
        required=True,
        help=(
            "One or more run config JSON files (path, or a bare filename inside "
            "configs/). Each config's results are located by hashing it."
        ),
    )
    parser.add_argument(
        "-o",
        "--output",
        dest="output",
        default="comparison.png",
        help="Output plot filename, written under plots/ (or an absolute path).",
    )
    parser.add_argument(
        "-e",
        "--exact",
        action="store_true",
        help="Score each instance against its own graph's optimum (exact beta).",
    )
    parser.add_argument(
        "-t",
        "--ignore_time_limit",
        action="store_true",
        help=(
            f"Ignore the {TIME_LIMIT}s time limit when deciding the Q-score "
            "(beta threshold only)."
        ),
    )
    parser.add_argument(
        "--show_minmax",
        action="store_true",
        help="Display min/max envelope shading",
    )
    parser.add_argument(
        "--minmax_lines",
        action="store_true",
        help="Overlay min/max envelope as dotted lines instead of filled shading",
    )
    parser.add_argument(
        "--show_stddev",
        action="store_true",
        help="Display +/-1 sigma shading",
    )
    parser.add_argument(
        "--stddev_lines",
        action="store_true",
        help="Overlay +/-1 sigma bounds as dotted lines",
    )
    parser.add_argument(
        "--log_time",
        action="store_true",
        help="Plot elapsed time on a logarithmic scale",
    )
    return parser.parse_args()


def _resolve_results(config: dict) -> str:
    """Locate the results file for a config via its content hash."""
    path = os.path.join(run_dir(config), RESULTS_FILE)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"No results found for config (hash={config_hash(config)}) at {path}. "
            "Run benchmark.py on this config first."
        )
    return path


def _beta(result: float, exact_result: float, random_score: float) -> float:
    """Q-score beta: 1 when the random baseline already hits the optimum."""
    if random_score == exact_result:
        return 1
    return (result - random_score) / (exact_result - random_score)


def _series_stats(per_size: list) -> dict:
    """Per-size min/max/mean/std arrays from a list of per-size value arrays."""
    return {
        "min": np.array([v.min() for v in per_size]),
        "max": np.array([v.max() for v in per_size]),
        "mean": np.array([v.mean() for v in per_size]),
        "std": np.array([v.std() for v in per_size]),
    }


class ExactBaselines:
    """Per-instance exact optima and random baselines, cached across configs.

    Keyed by the sweep identity ``(problem_type, size, seed, count)``: configs
    that ran the same sweep share the same instances, so the (expensive) exact
    solve happens once no matter how many solvers are being plotted.
    """

    def __init__(self) -> None:
        self._cache: dict[tuple, tuple[list, list]] = {}

    def for_size(
        self, problem_type: str, size: int, seed: int | None, count: int
    ) -> tuple[list, list]:
        """Return ``(exact_optima, random_scores)`` for one size's instances."""
        key = (problem_type, size, seed, count)
        if key in self._cache:
            return self._cache[key]

        # Logged here, not per config, so the output reflects work actually done:
        # configs that share a sweep reuse this result.
        print(f"Solving size {size} exactly (seed {seed}, {count} instances)")
        instance_seed = seed
        exact_scores, random_scores = [], []
        for _ in range(count):
            graph = sample_instance_graph(size, instance_seed)
            exact_scores.append(exact_optimum(problem_type, graph))
            if problem_type == "max-cut":
                # Deterministic closed form; no sampling needed.
                random_scores.append(size * (size - 1) / 8)
            else:
                # Sampled baseline -- seeded so the plot is reproducible.
                random_scores.append(
                    average_naive_clique_size(
                        graph, seed=derive_seed(instance_seed, "beta")
                    )
                )
            if instance_seed is not None:
                instance_seed += 1

        self._cache[key] = (exact_scores, random_scores)
        return self._cache[key]


def _prepare_dataset(
    data: dict,
    config: dict,
    exact: bool,
    ignore_time_limit: bool,
    baselines: ExactBaselines | None = None,
) -> dict | None:
    """Compute beta/time statistics for one run.

    Run inputs (problem type, solver, seed) come from ``config``; ``data`` holds
    only the per-size results written by the sweep.
    """
    problem_range = np.array(
        sorted(
            int(k)
            for k, v in data.items()
            if isinstance(v, dict) and v.get("result") not in (None, [])
        )
    )
    if problem_range.size == 0:
        return None

    problem_type = config["problem_type"]
    solver = config["solver"]
    baselines = baselines or ExactBaselines()

    betas_per_size, times_per_size, plotted_sizes = [], [], []

    if exact:
        seed = config.get("sweep", {}).get("seed")
        for size in problem_range:
            results = np.array(data[str(size)]["result"])
            times = np.array(data[str(size)]["times"])
            if len(results) == 0:
                continue

            exact_scores, random_scores = baselines.for_size(
                problem_type, int(size), seed, len(results)
            )
            # A sweep run with --exact stores its own optima; prefer them.
            if "exact-result" in data[str(size)]:
                exact_scores = data[str(size)]["exact-result"]

            betas_per_size.append(
                np.array(
                    [
                        _beta(result, exact_score, random_score)
                        for result, exact_score, random_score in zip(
                            results, exact_scores, random_scores, strict=True
                        )
                    ]
                )
            )
            times_per_size.append(times)
            plotted_sizes.append(size)
            if seed is not None:
                seed += len(results)
    else:
        beta_fn = (
            calculate_beta_max_cut
            if problem_type == "max-cut"
            else calculate_beta_max_clique
        )
        for size in problem_range:
            results = np.array(data[str(size)]["result"])
            times = np.array(data[str(size)]["times"])
            times = times[~np.isnan(results)]
            results = results[~np.isnan(results)]

            if len(results) == 0:
                continue

            betas_per_size.append(
                np.array([beta_fn(size, result) for result in results])
            )
            times_per_size.append(times)
            plotted_sizes.append(size)

    if not plotted_sizes:
        return None

    beta_stats = _series_stats(betas_per_size)
    time_stats = _series_stats(times_per_size)
    problem_range = np.array(plotted_sizes)

    beta_passes = beta_stats["mean"] > BETA_THRESHOLD
    passes = beta_passes.copy()
    if not ignore_time_limit:
        in_time = time_stats["mean"] < TIME_LIMIT
        passes &= in_time
        # A size can clear the beta threshold and still be excluded for time.
        # `sweep.timeout` is the measurement budget and TIME_LIMIT is the Q-score
        # criterion; they need not agree, so say it rather than silently capping.
        for size, ok_beta, ok_time, mean_time in zip(
            problem_range, beta_passes, in_time, time_stats["mean"], strict=True
        ):
            if ok_beta and not ok_time:
                print(
                    f"  N={size}: mean beta clears {BETA_THRESHOLD} but mean time "
                    f"{mean_time:.1f}s exceeds the {TIME_LIMIT}s Q-score limit "
                    f"(-t ignores it)"
                )

    # The Q-score is the largest N that passes *with every smaller size also
    # passing*, so it stops at the first failure. The Atos definition ("largest N
    # with mean beta above the threshold") assumes beta decreases with N, which
    # makes the two readings identical -- but a solver whose beta dips below the
    # line and recovers would otherwise be credited with the larger size it cannot
    # reliably solve.
    qscore = None
    for size, ok in zip(problem_range, passes, strict=True):
        if not ok:
            break
        qscore = int(size)

    return {
        "problem_range": problem_range,
        "mins_beta": beta_stats["min"],
        "maxes_beta": beta_stats["max"],
        "means_beta": beta_stats["mean"],
        "stds_beta": beta_stats["std"],
        "mins_time": time_stats["min"],
        "maxes_time": time_stats["max"],
        "means_time": time_stats["mean"],
        "stds_time": time_stats["std"],
        "problem_type": problem_type,
        "solver": solver,
        "qscore": qscore,
    }


def _plot_series(
    ax,
    x,
    mins,
    maxes,
    mean,
    lower_std,
    upper_std,
    color,
    label,
    *,
    show_minmax: bool,
    minmax_lines: bool,
    show_stddev: bool,
    stddev_lines: bool,
) -> None:
    """Draw one run's envelope and mean line on an axis (beta or time)."""
    if show_minmax:
        ax.fill_between(x, mins, maxes, color=color, alpha=0.1)
    if minmax_lines:
        for y in (mins, maxes):
            ax.plot(x, y, color=color, linestyle=":", linewidth=1, alpha=0.8)
    if show_stddev:
        ax.fill_between(x, lower_std, upper_std, color=color, alpha=0.2)
    if stddev_lines:
        for y in (lower_std, upper_std):
            ax.plot(x, y, color=color, linestyle="--", linewidth=1, alpha=0.8)
    ax.plot(x, mean, color=color, marker="o", linewidth=2, label=label)


def plot_graphs(
    configs: list,
    output: str = "comparison.png",
    exact: bool = False,
    ignore_time_limit: bool = False,
    show_minmax: bool = False,
    minmax_lines: bool = False,
    show_stddev: bool = False,
    stddev_lines: bool = False,
    log_time: bool = False,
) -> str | None:
    """Plot beta vs N and elapsed time vs N for the given runs.

    Args:
        configs: run config paths (or bare filenames inside ``configs/``).
        output: plot filename, written under ``plots/`` (or an absolute path).
        exact: score each instance against its own optimum instead of the
            asymptotic baselines. Only suitable at small sizes.
        ignore_time_limit: decide the Q-score on beta alone, ignoring the
            per-instance time limit.
        show_minmax: shade the min/max envelope.
        minmax_lines: draw the min/max envelope as dotted lines.
        show_stddev: shade +/-1 standard deviation.
        stddev_lines: draw +/-1 standard deviation as dotted lines.
        log_time: use a logarithmic time axis.

    Returns:
        The path the figure was written to, or ``None`` if there was nothing to
        plot.

    Raises:
        ValueError: if the configs mix problem types.
    """
    baselines = ExactBaselines()
    datasets = []
    for config_arg in configs:
        try:
            config = load_config(config_arg)
            file_path = _resolve_results(config)
        except FileNotFoundError as exc:
            print(exc)
            continue

        with open(file_path, encoding="utf-8") as json_file:
            data = json.load(json_file)

        stats = _prepare_dataset(data, config, exact, ignore_time_limit, baselines)
        if stats is None:
            print(f"No valid data points found for {config_arg}; skipping.")
            continue

        stats["file_path"] = file_path
        # Label comes from the config's `name`; fall back to the solver.
        stats["label"] = config.get("name") or stats["solver"]
        datasets.append(stats)

    if not datasets:
        print("No datasets available for plotting.")
        return None

    problem_types = {dataset["problem_type"] for dataset in datasets}
    if len(problem_types) != 1:
        raise ValueError(
            "All datasets must have the same problem_type to be plotted together."
        )
    problem_type = problem_types.pop()

    all_sizes = sorted(
        {size for dataset in datasets for size in dataset["problem_range"]}
    )
    x_min = max(min(all_sizes) - 1, 0)
    x_max = max(all_sizes) + 1
    time_ylim = min(
        90, max(np.max(dataset["maxes_time"]) for dataset in datasets) * 1.2
    )
    min_time_observed = min(np.min(dataset["mins_time"]) for dataset in datasets)
    if show_minmax:
        beta_max_candidate = max(np.max(dataset["maxes_beta"]) for dataset in datasets)
    else:
        beta_max_candidate = max(
            np.max(dataset["means_beta"] + dataset["stds_beta"]) for dataset in datasets
        )
    beta_ylim_upper = max(0.5, min(1.25, beta_max_candidate * 1.1))

    fig, axs = plt.subplots(1, 2, figsize=(12, 6))
    fig.suptitle(f"Q-score {problem_type} comparison ({len(datasets)} configurations)")

    color_cycle = cycle(
        plt.rcParams["axes.prop_cycle"].by_key().get("color", ["tab:blue"])
    )
    for dataset in datasets:
        color = next(color_cycle)
        problem_range = dataset["problem_range"]
        qscore_label = dataset["qscore"] if dataset["qscore"] is not None else "N/A"

        beta_lower_std = dataset["means_beta"] - dataset["stds_beta"]
        beta_upper_std = dataset["means_beta"] + dataset["stds_beta"]
        if exact:
            beta_upper_std = np.minimum(beta_upper_std, 1.0)
        _plot_series(
            axs[0],
            problem_range,
            dataset["mins_beta"],
            dataset["maxes_beta"],
            dataset["means_beta"],
            beta_lower_std,
            beta_upper_std,
            color,
            f"{dataset['label']} (Q={qscore_label})",
            show_minmax=show_minmax,
            minmax_lines=minmax_lines,
            show_stddev=show_stddev,
            stddev_lines=stddev_lines,
        )

        _plot_series(
            axs[1],
            problem_range,
            dataset["mins_time"],
            dataset["maxes_time"],
            dataset["means_time"],
            np.maximum(dataset["means_time"] - dataset["stds_time"], 0),
            dataset["means_time"] + dataset["stds_time"],
            color,
            dataset["label"],
            show_minmax=show_minmax,
            minmax_lines=minmax_lines,
            show_stddev=show_stddev,
            stddev_lines=stddev_lines,
        )

    axs[0].set_title(f"Beta {'(exact)' if exact else '(asymptotic)'}")
    axs[0].set(
        xlabel="Problem size N",
        ylabel="Beta",
        xlim=[x_min, x_max],
        ylim=[-0.15, beta_ylim_upper],
    )
    axs[0].set_xticks(all_sizes)
    axs[0].axhline(y=BETA_THRESHOLD, color="r", linestyle="--")
    axs[0].set_axisbelow(True)
    axs[0].grid()

    axs[1].set_title("Elapsed time")
    if log_time:
        axs[1].set_yscale("log")
        lower_time_ylim = max(1e-2, min_time_observed * 0.8)
    else:
        lower_time_ylim = 0
    axs[1].set(
        xlabel="Problem size N",
        ylabel="Time (in s)",
        xlim=[x_min, x_max],
        ylim=[lower_time_ylim, max(time_ylim, 1)],
    )
    axs[1].set_xticks(all_sizes)
    # Only draw the limit when it is on-scale, so its absence is not mistaken
    # for a run that sits just under it.
    if max(time_ylim, 1) >= TIME_LIMIT:
        axs[1].axhline(y=TIME_LIMIT, color="r", linestyle="--")
    axs[1].set_axisbelow(True)
    axs[1].grid()

    axs[0].legend(loc="lower right")
    axs[1].legend(loc="upper left")

    if os.path.isabs(output):
        out_path = output
    else:
        os.makedirs(PLOTS_DIR, exist_ok=True)
        out_path = os.path.join(PLOTS_DIR, output)
    plt.savefig(out_path)
    print(f"Saved plot to {out_path}")
    return out_path


def main() -> None:
    """Entry point for ``python plotter.py``."""
    args = parse_args()
    plot_graphs(
        args.configs,
        args.output,
        args.exact,
        args.ignore_time_limit,
        args.show_minmax,
        args.minmax_lines,
        args.show_stddev,
        args.stddev_lines,
        args.log_time,
    )


if __name__ == "__main__":
    main()
