"""
train_pinn_aerofoil.py

Minimal PyTorch PINN training script for steady 2D Euler around NACA0012.

- Loads the .npy files generated by generate_aerofoil_training_sets.py
- Builds a small MLP mapping (x,y) -> (rho, u, v, T)
- Computes PDE residual for steady 2D Euler: div G(U) = 0
- Applies shock-adaptive weight lambda based on div(u)
- Loss = L_BC + L_data_internal + L_F
- Optimizes with Adam then LBFGS

Notes:
- No quantum branch is implemented here. If you want HQPINN, you would add a parallel PQC branch and fuse outputs.
- If you have CFD fields, load them and fill arrays for X_data_int + targets.
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# ----------------------------
# Config
# ----------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
gamma = 1.4
R_gas = 287.0  # only used if working in SI; if nondim, adapt accordingly

# file names produced by generate_aerofoil_training_sets.py
X_in_file = "X_in.npy"
X_out_file = "X_out.npy"
X_top_file = "X_top.npy"
X_bot_file = "X_bot.npy"
X_wall_file = "X_wall.npy"
X_wall_normals_file = "X_wall_normals.npy"
X_f_file = "X_f.npy"
X_data_int_file = "X_data_int.npy"

# training hyperparams
lr = 5e-4
adam_steps = 40000
lbfgs_max_iter = 2000
epsilon_lambda = 0.1  # shock weighting parameter


# ----------------------------
# Utilities: load datasets
# ----------------------------
def load_points(fname):
    return torch.tensor(np.load(fname), dtype=torch.float32, device=device)


X_in = load_points(X_in_file)  # shape (N_in, 2)
X_out = load_points(X_out_file)
X_top = load_points(X_top_file)
X_bot = load_points(X_bot_file)
X_wall = load_points(X_wall_file)
X_wall_normals = torch.tensor(
    np.load(X_wall_normals_file), dtype=torch.float32, device=device
)
X_f = load_points(X_f_file)  # PDE collocation
X_data_int = load_points(
    X_data_int_file
)  # supervised internal (if you have CFD targets)

# ----------------------------
# If you have CFD targets for X_data_int and boundaries, load them here.
# For example, if you received arrays rho_cfd.npy, u_cfd.npy, v_cfd.npy, T_cfd.npy:
#   Y_data_int = torch.stack([rho_cfd, u_cfd, v_cfd, T_cfd], dim=-1)
# If you don't have CFD, set Y_data_int = None
# ----------------------------
Y_data_int = None
# Example placeholder: if you had a file "Y_data_int.npy" with shape (N_data_int,4)
# try:
#    Y_data_int = torch.tensor(np.load("Y_data_int.npy"), dtype=torch.float32, device=device)
# except FileNotFoundError:
#    Y_data_int = None

# For boundaries, if you have BC target values (paper: inlet values given, top/bottom periodic, wall no-penetration)
# Define inlet target (SI values from paper)
# inlet: rho=1.225 kg/m3, u=272.15 m/s, v=0, T=288.15 K (paper in SI)
U_in_values = torch.tensor(
    [1.225, 272.15, 0.0, 288.15], dtype=torch.float32, device=device
)


# ----------------------------
# PINN model (MLP)
# ----------------------------
class MLP_PINN(nn.Module):
    def __init__(self, hidden_layers=4, hidden_units=40):
        super().__init__()
        layers = []
        in_dim = 2
        out_dim = 4  # rho, u, v, T
        layers.append(nn.Linear(in_dim, hidden_units))
        layers.append(nn.Tanh())
        for _ in range(hidden_layers - 1):
            layers.append(nn.Linear(hidden_units, hidden_units))
            layers.append(nn.Tanh())
        layers.append(nn.Linear(hidden_units, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)  # raw outputs for rho,u,v,T


model = MLP_PINN(hidden_layers=4, hidden_units=40).to(device)


# Helper: enforce positivity optionally (paper DOES NOT use softplus; we keep raw outputs)
def postprocess_output(raw):
    # raw: (N,4) -> rho, u, v, T
    # Optional positivity: uncomment softplus lines if you want to guarantee positives
    rho = raw[:, 0:1]  # optionally: torch.softplus(raw[:,0:1]) + 1e-3
    u = raw[:, 1:2]
    v = raw[:, 2:3]
    T = raw[:, 3:4]  # optionally: torch.softplus(raw[:,3:4]) + 1e-3
    return rho, u, v, T


# ----------------------------
# Differential helpers (autograd)
# ----------------------------
def gradients(u, x, order=1):
    """
    Compute gradients of u wrt x using torch.autograd.
    u: (N,1) tensor, x: (N,2) requires_grad True
    returns du/dx as (N,2) tensor for order=1.
    """
    if not x.requires_grad:
        x.requires_grad_(True)
    grads = torch.autograd.grad(
        outputs=u,
        inputs=x,
        grad_outputs=torch.ones_like(u),
        create_graph=True,
        retain_graph=True,
        only_inputs=True,
    )[0]
    return grads


# ----------------------------
# PDE residual (steady Euler): div G(U) = 0
# conservative variables built from primitives
# ----------------------------
def euler_residual(xy):
    """
    Compute residual vector R(x,y) = d/dx[G1(U)] + d/dy[G2(U)]
    where U = [rho, rho*u, rho*v, rho*E]
    Input: xy (N,2) Tensor with requires_grad True
    Output: R (N,4) tensor (residual for each conservation equation)
    """
    xy = xy.clone().detach().requires_grad_(True)
    raw = model(xy)  # (N,4)
    rho, u, v, T = postprocess_output(raw)
    # compute derived quantities
    p = rho * R_gas * T
    E = p / ((gamma - 1.0) * rho) + 0.5 * (u**2 + v**2)
    # conservative variables
    rho_u = rho * u
    rho_v = rho * v
    rho_E = rho * E
    # fluxes G1, G2 (each (N,4) columns)
    # G1 = [rho*u, p + rho*u^2, rho*u*v, p*u + rho*u*E]
    G1 = torch.cat([rho_u, p + rho * u**2, rho * u * v, p * u + rho * u * E], dim=1)
    # G2 = [rho*v, rho*u*v, p + rho*v^2, p*v + rho*v*E]
    G2 = torch.cat([rho_v, rho * u * v, p + rho * v**2, p * v + rho * v * E], dim=1)
    # compute spatial derivatives
    # for each component of G1 and G2, compute d/dx and d/dy
    R = []
    # compute d/dx G1 and d/dy G2
    for i in range(4):
        Gi1 = G1[:, i : i + 1]
        Gi2 = G2[:, i : i + 1]
        dG1_dx = gradients(Gi1, xy)[:, 0:1]  # d/dx component
        dG2_dy = gradients(Gi2, xy)[:, 1:2]  # d/dy component
        R_comp = dG1_dx + dG2_dy
        R.append(R_comp)
    R = torch.cat(R, dim=1)  # shape (N,4)
    return R, rho, u, v, T


# ----------------------------
# Shock-adaptive lambda weight
# ----------------------------
def compute_lambda(xy):
    """
    Compute per-point lambda weight based on divergence of velocity:
    lambda = 1 / (eps * (|div| - div) + 1)
    where div = u_x + v_y
    """
    xy = xy.clone().detach().requires_grad_(True)
    raw = model(xy)
    _, u, v, _ = postprocess_output(raw)
    u_x = gradients(u, xy)[:, 0:1]
    v_y = gradients(v, xy)[:, 1:2]
    div = u_x + v_y
    lam = 1.0 / (epsilon_lambda * (torch.abs(div) - div) + 1.0)
    # clamp to reasonable range to avoid tiny weights
    lam = torch.clamp(lam, min=1e-4, max=1.0)
    return lam


# ----------------------------
# Loss functions (BCs, PDE, internal data)
# ----------------------------
mse = nn.MSELoss()


def loss_boundary():
    # inlet Dirichlet on full primitive state
    pred_in = model(X_in)
    rho_i, u_i, v_i, T_i = postprocess_output(pred_in)
    U_pred_in = torch.cat([rho_i, u_i, v_i, T_i], dim=1)
    L_in = mse(U_pred_in, U_in_values.expand(U_pred_in.shape[0], -1))
    # wall: no-penetration u·n = 0
    pred_wall = model(X_wall)
    rho_w, u_w, v_w, T_w = postprocess_output(pred_wall)
    normals = Xw_normals = Xw_normals = X_wall_normals[:, 2:4]  # (N_wall,2)
    pen = u_w * normals[:, 0:1] + v_w * normals[:, 1:2]  # (N_wall,1)
    L_wall = mse(pen, torch.zeros_like(pen))
    # top/bottom periodic: enforce U(x, top) == U(x, bot)
    pred_top = model(X_top)
    pred_bot = model(X_bot)
    rho_t, u_t, v_t, T_t = postprocess_output(pred_top)
    rho_b, u_b, v_b, T_b = postprocess_output(pred_bot)
    U_top = torch.cat([rho_t, u_t, v_t, T_t], dim=1)
    U_bot = torch.cat([rho_b, u_b, v_b, T_b], dim=1)
    L_per = mse(U_top, U_bot)
    # outlet: enforce pressure at outlet if you have a reference; else weakly enforce p ~ p_inf or ignore
    # Here we skip outlet pressure enforcement unless you supply p_out values from CFD.
    L_out = torch.tensor(0.0, device=device)
    return L_in + L_wall + L_per + L_out


def loss_internal_data():
    if Y_data_int is None:
        return torch.tensor(0.0, device=device)
    pred = model(X_data_int)
    rho_p, u_p, v_p, T_p = postprocess_output(pred)
    Y_pred = torch.cat([rho_p, u_p, v_p, T_p], dim=1)
    return mse(Y_pred, Y_data_int)


def loss_pde():
    R, _, _, _, _ = euler_residual(X_f)
    lam = compute_lambda(X_f)  # shape (N_pde,1)
    # weight residual pointwise: L_F = mean( lam * sum(R^2 over eqns) )
    R2 = torch.sum(R**2, dim=1, keepdim=True)
    weighted = lam * R2
    return torch.mean(weighted)


# ----------------------------
# Training loop: Adam then LBFGS
# ----------------------------
optimizer = optim.Adam(model.parameters(), lr=lr)

print("Starting Adam...")
for step in range(1, adam_steps + 1):
    optimizer.zero_grad()
    L_bc = loss_boundary()
    L_data = loss_internal_data()
    L_f = loss_pde()
    L_total = L_bc + L_data + L_f
    L_total.backward()
    optimizer.step()
    if step % 500 == 0:
        print(
            f"Step {step}/{adam_steps}  Loss={L_total.item():.6e}  BC={L_bc.item():.3e}  Data={L_data.item():.3e}  PDE={L_f.item():.3e}"
        )

# LBFGS refinement
print("Switching to L-BFGS...")


def closure():
    optimizer_lbfgs.zero_grad()
    L_bc = loss_boundary()
    L_data = loss_internal_data()
    L_f = loss_pde()
    L_total = L_bc + L_data + L_f
    L_total.backward()
    return L_total


optimizer_lbfgs = optim.LBFGS(
    model.parameters(),
    max_iter=lbfgs_max_iter,
    lr=1.0,
    tolerance_grad=1e-7,
    tolerance_change=1e-12,
)

optimizer_lbfgs.step(closure)

print("Training finished.")

# ----------------------------
# Save model
# ----------------------------
torch.save(model.state_dict(), "pinn_aerofoil_model.pt")
print("Model saved to pinn_aerofoil_model.pt")
